import Head from 'next/head'
import {useStorage} from "@/context/StorageContext"
// Layouts
import LoginLayout from "@/layouts/auth/LoginLayout"
import AdminLayout from "@/layouts/users/AdminLayout"
import ClientLayout from "@/layouts/users/ClientLayout"
import ProfessionalLayout from "@/layouts/users/ProfessionalLayout"

const Home = () => {
  let title = "Sign In"
  let authData = null
  const REMEMBER_USER = false

  if (typeof window === "undefined") {
    return <h1>Loading...</h1>
  } else {
    const {getStorage} = useStorage()
    const storageType = !REMEMBER_USER && "session"
    authData = getStorage({type: storageType, key: "AUTH"})
    authData = JSON.parse(authData)
    title = authData && "Home"
  }

  const isProfessional = (authData && authData.userRole === "professional")

  return (
    <main>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      {
        isProfessional ? <ProfessionalLayout/> :
        <LoginLayout/>
      }
      {/* { */}
      {/*   isAdmin ? <AdminLayout/> */}
      {/*   : isClient ? <ClientLayout/> */}
      {/*   : <LoginLayout/> */}
      {/* } */}
    </main>
  )
}

export default Home
