import Head from 'next/head'
import {useAppState} from "@/context/AppStateContext"
// Layouts
import LoginLayout from "@/layouts/auth/LoginLayout"
import AdminLayout from "@/layouts/users/AdminLayout"
import ClientLayout from "@/layouts/users/ClientLayout"
import ProfessionalLayout from "@/layouts/users/ProfessionalLayout"

const Home = () => {
  const {state, dispatch} = useAppState()
  // const title = token ? "Home" : "Sign In"
  //
  // const isAdmin = token && role === "ADMIN"
  // const isClient = token && role === "CLIENT"
  // const isProfessional = token && role === "PROFESSIONAL"

  return (
    <main>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <LoginLayout/>
      {/* { */}
      {/*   isAdmin ? <AdminLayout/> */}
      {/*   : isClient ? <ClientLayout/> */}
      {/*   : isProfessional ? <ProfessionalLayout/> */}
      {/*   : <LoginLayout/> */}
      {/* } */}
    </main>
  )
}

export default Home
