import Head from 'next/head'
import {useAuth} from "@/context/AuthContext"
import {useStorage} from "@/context/StorageContext"
// Layouts
import LoadingLayout from "@/layouts/LoadingLayout"
import LoginLayout from "@/layouts/auth/LoginLayout"
import AdminLayout from "@/layouts/users/AdminLayout"
import ClientLayout from "@/layouts/users/ClientLayout"
import ProfessionalLayout from "@/layouts/users/ProfessionalLayout"

const Home = () => {
  let title = "Sign In"
  let authData = null
  const REMEMBER_USER = false
  const {isUserRole} = useAuth()

  if (typeof window === "undefined")
    return <LoadingLayout/>
  else {
    const {getStorage} = useStorage()
    const storageType = !REMEMBER_USER && "session"
    authData = getStorage({type: storageType, key: "AUTH"})
    authData = JSON.parse(authData)
    title = authData && "Home"
  }

  const isAdmin = isUserRole(authData, 'admin')
  const isClient= isUserRole(authData, 'client')
  const isProfessional = isUserRole(authData, 'professional')

  return (
    <main>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      {
        isProfessional ? <ProfessionalLayout/> :
        isClient ? <ClientLayout/> :
        isAdmin ? <AdminLayout/> :
        <LoginLayout/>
      }
    </main>
  )
}

export default Home
