import Head from 'next/head'
import {login} from "@/api/authApi"
import {useMutation} from "react-query"
import AuthLayout from "@/layouts/AuthLayout"
import inputList from "@/constants/auth/loginInputs"

const Login = () => {
  const {
    isLoading, isError,
    mutateAsync, data, error
  } = useMutation("login", login)

  const submitHandler = async data => {
    console.log("submitted data: ", data)
    await mutateAsync({...data})
  }

  const linkTo = {
    href: "/signup",
    text: "No Account?",
    linkText: "Join now"
  }

  return (
    <main>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout 
        isLoginPage
        linkTo={linkTo}
        heading="Sign In"
        submitValue="Login"
        isLoading={isLoading}
        inputList={inputList}
        submitHandler={submitHandler}
      />
    </main>
  )
}

export default Login
