import Head from 'next/head'
import AuthLayout from "@/layouts/AuthLayout"
import {loginFields as fields} from "@/constants/authInputFields"

const Login = () => {
  const submitHandler = data => {
    console.log("submitted data: ", data)
  }

  return (
    <main>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout 
        heading="Sign In"
        fields={fields}
        buttonLabel="Login"
        submitHandler={submitHandler}
      />
    </main>
  )
}

export default Login
